<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Contracts\Harem.Contracts.Configurations\Harem.Contracts.Configurations.csproj" />
        <ProjectReference Include="..\..\Contracts\Harem.Contracts.Domain\Harem.Contracts.Domain.csproj" />
        <ProjectReference Include="..\..\Services\Harem.Services.Abstractions\Harem.Services.Abstractions.csproj" />
        <ProjectReference Include="..\..\Services\Harem.Services.Channels\Harem.Services.Channels.csproj" />
        <ProjectReference Include="..\Harem.Chats.Abstractions\Harem.Chats.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mattermost.Net" Version="5.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.8" />
    </ItemGroup>

</Project>
